### ISSUE TITLE
could you update MVVMToolkitExtensions.WPF.Demo?

### ISSUE THREAD

**Issue by asine** [BrandonWoodward/MVVMToolkitExtensions#1]
could you update MVVMToolkitExtensions.WPF.Demo? thanks

**Comment by BrandonWoodward** [comment]
The demo is no longer part of the repo. Any examples and documentation for WPF is now located [here](https://brandonwoodward.github.io/MVVMToolkitExtensions/articles/wpf/setup.html) which should cover everything. If there's any issues let me know.
